<?php

Route::group(['middleware' => ['web']], function(){
  Route::get('/', 'PagesController@index')->middleware('checkuser');
  Route::get('search', 'StudentsController@search')->middleware('checkuser');
  Route::get('login', 'PagesController@login')->middleware('logincheck');
  Route::get('register', 'PagesController@register')->middleware('logincheck');
  Route::post('register', 'CompaniesController@register');
  Route::get('departments/add', 'DepartmentsController@add')->middleware('checkuser');
  Route::get('departments', 'DepartmentsController@index')->middleware('checkuser');
  Route::get('u_adminpanel', 'PagesController@u_adminPanel')->middleware('checkuser');
  Route::post('login', 'LoginController@authenticate');
  Route::get('logout', 'LoginController@logout');
  Route::post('department/actions/add', 'DepartmentsController@store')->middleware('checkuser');
  Route::get('school/{school}/departments/', 'DepartmentsController@showDepartments')->middleware('checkuser');
  Route::patch('departments/update/{department}', 'DepartmentsController@update')->middleware('checkuser');
  Route::delete('departments/delete/{department}' , 'DepartmentsController@delete')->middleware('checkuser');
  Route::get('students/add', 'PagesController@addStudent')->middleware('checkuser');
  Route::post('students/add', 'StudentsController@add')->middleware('checkuser');
  Route::get('students/view', 'StudentsController@view')->middleware('checkuser');
  Route::patch('students/update/{student}', 'StudentsController@update')->middleware('checkuser');
  Route::delete('students/delete/{student}', 'StudentsController@delete')->middleware('checkuser');
  Route::get('school/{school}/departments/{department}/students', 'StudentsController@studentList')->middleware('checkuser');
  Route::get('adminpanel', 'PagesController@adminpanel')->middleware('checkuser');
  Route::get('adminpanel/schools/add', 'PagesController@addSchool')->middleware('checkuser');
  Route::post('adminpanel/schools/add', 'SchoolsController@add')->middleware('checkuser');
  Route::get('editprofile', 'PagesController@editProfile')->middleware('checkuser');
  Route::get('forgotpassword', 'PagesController@forgotPassword');
  Route::post('forgotpassword', 'LoginController@forgotPassword');
  Route::get('addskill/{id}', 'SkillsController@add')->middleware('checkuser');
  Route::get('updatesummary/{student}', 'StudentsController@updateSummary')->middleware('checkuser');
  Route::get('updateexperience/{student}', 'ExperienceController@update')->middleware('checkuser');
  Route::get('updateeducation/{student}', 'EducationsController@update')->middleware('checkuser');
  Route::get('updateskill', 'SkillsController@update')->middleware('checkuser');
  Route::get('deleteskill', 'SkillsController@delete')->middleware('checkuser');
  Route::get('updateprofile/{student}', 'StudentsController@updateProfile')->middleware('checkuser');
  Route::patch('updatephoto/{student}', 'StudentsController@updatePhoto')->middleware('checkuser');
  Route::patch('updatecompanyphoto/{company}', 'CompaniesController@updatePhoto')->middleware('checkuser');
  Route::get('/deleterec/{rec}', 'RecommendationsController@delete')->middleware('checkuser');
  Route::get('managecompanies', 'PagesController@managecompanies');
  Route::get('/managecompanies/approve', 'CompaniesController@approve')->middleware('checkuser');
  Route::get('/managecompanies/disapprove', 'CompaniesController@disapprove')->middleware('checkuser');
  Route::get('editaccount', 'PagesController@editaccount')->middleware('checkuser');
  Route::patch('editaccount', 'LoginController@editaccount')->middleware('checkuser');
  Route::get('adminpanel/schools/view', 'PagesController@viewschools')->middleware('checkuser');
  Route::get('deleteschool', 'SchoolsController@delete')->middleware('checkuser');
  Route::get('adminpanel/recommendations', 'PagesController@recommendations')->middleware('checkuser');
  Route::get('recommendations/approve', 'RecommendationsController@approverec')->middleware('checkuser');
  Route::get('recommendations/rejectrec', 'RecommendationsController@rejectrec')->middleware('checkuser');
  Route::get('recommendations/undoapprove', 'RecommendationsController@undoapprove')->middleware('checkuser');
  Route::get('sendchat', 'ChatsController@send')->middleware('checkuser');
  Route::get('loadchats', 'ChatsController@loadchats')->middleware('checkuser');
  Route::get('loadtargetchat', 'ChatsController@loadtargetchat')->middleware('checkuser');
  Route::get('loadstudentchat', 'ChatsController@loadstudentchat')->middleware('checkuser');
  Route::get('refreshcompanychats', 'ChatsController@refreshcompanychats')->middleware('checkuser');
  Route::get('markcompanychatsasread', 'ChatsController@markcompanychatsasread')->middleware('checkuser');
  Route::get('markstudentchatsasread', 'ChatsController@markstudentchatsasread')->middleware('checkuser');
  Route::get('refreshstudentchats', 'ChatsController@refreshstudentchats')->middleware('checkuser');
  Route::get('countmessages', 'ChatsController@countmessages')->middleware('checkuser');
  Route::get('updatecompanyinfo', 'CompaniesController@updatecompanyinfo')->middleware('checkuser');
  Route::get('deletestudentconvo', 'ChatsController@deletestudentconvo')->middleware('checkuser');
  Route::get('resetpassword', 'PagesController@resetpassword');
  Route::post('resetpassword', 'LoginController@resetpassword');
  Route::get('c/{username}', 'PagesController@viewcompany')->middleware('checkuser');
// This must always be on bottom. It causes errors if not. AND I KNOW WHY
  Route::get('/{username}', 'StudentsController@studentProfile')->middleware('checkuser');
  Route::post('/{studentid}', 'RecommendationsController@add')->middleware('checkuser');
});
